export const ITEMS_REQUEST = 'ITEMS_REQUEST'
export const ITEMS_SUCCESS = 'ITEMS_SUCCESS'
export const ITEMS_FAIL = 'ITEMS_FAIL'

export const ITEMS_DESC_REQUEST = 'ITEMS_DESC_REQUEST'
export const ITEMS_DESC_SUCCESS = 'ITEMS_DESC_SUCCESS'
export const ITEMS_DESC_FAIL = 'ITEMS_DESC_FAIL'

